---
title: "A3"
author: "Yifei.Peng"
date: "2021/4/13"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
chooseCRANmirror(graphics=FALSE, ind=1)
knitr::opts_chunk$set(error = TRUE)
library(pastecs)
library(tidyverse) 
library(data.table)
library(stringr)
library(mfx)
library(MASS)
library(bayesm)
library(rmarkdown)
library(ggplot2)
library(dplyr)
library(lubridate)
library(plm)
setwd('C:/Users/sophi/Desktop/Econ613/A3')
options(knitr.purl.inline = TRUE)
```
```{r data}
ppl_ori = read.csv('population.csv')
crm_ori = read.csv('crime_long.csv')
off_ori = read.csv('officers.csv')
```
```{r}
summary(ppl_ori)
```
```{r}
head(ppl_ori)
```


```{r}
summary(crm_ori)
```

```{r}
#Ex2 data manipulate
ppl = ppl_ori
crm = crm_ori
tot_crm_mon = aggregate(crimes~crime_month,crm,sum)
head(tot_crm_mon)
```


```{r}
tot_crm_mon$crime_month = ymd(tot_crm_mon$crime_month)
plot1 = ggplot(tot_crm_mon, aes(x = crime_month, y = crimes)) + geom_line()+ scale_x_date(date_breaks = '24 months', date_labels = '%m %Y')
plot1
```
```{r include = FALSE}
# use the form of above aggregate(), would not have to rename the column anymore
```

```{r }
# merge
ppl_crm = left_join(ppl, crm, by = c('district'='district', 'month'='crime_month'))
head(ppl_crm,10)
```

```{r}
# panel data of unit

# sum up the crime_type
a <- ppl_crm %>%group_by( , month, period, district, tot_pop, tot_white, tot_black, tot_hisp, p50_inc, crime_type) %>% summarise(,crimes=sum(crimes))
b <- spread(a, crime_type,crimes) %>% mutate(, tot_crimes = drug + other + property + violent, tot_crm_p_res = tot_crimes/tot_pop, vio_crm_p_res = violent/tot_pop, pro_crm_p_res = property/tot_pop, ro_black = tot_black/tot_pop, ro_hisp = tot_hisp/tot_pop, ro_white = tot_white/tot_pop)
panel5 = b[,c(1:3,15:17,8, 18:20)]#district,tot_crm_p_res,vio_crm_p_res, pro_crm_p_res, p50_inc,ro_black,ro_hisp, ro_white)
head(panel5,15)
```

```{r}
#Ex3

#pool estimation
off = off_ori
panel5_3 = cbind(panel5, b$tot_crimes) %>% rename(,c("tot_crimes" = "...11"))
offcri= left_join(off, panel5_3, by=c("unit"="district" , "month"="month"))
tot_crimes = unlist(offcri$tot_crimes)
offcri = data.frame(offcri[,1:13], tot_crimes)

reg1 <- plm(arrest ~ tenure + p50_inc + tot_crimes + ro_black + ro_hisp + ro_white, data = offcri, model = "pooling")
summary(reg1)
```


As the result shown above, when using the pooling method and does not use the fixed effect or random effect model, The result is not significant. 
```{r}
#Ex4
#using within estimator

reg2 = plm(arrest ~ tenure + p50_inc + tot_crimes + ro_black + ro_hisp + ro_white, data = offcri, model = "within", index = c("month"))

summary(reg2)
```

```{r}
#Ex5
#Q1
reg5_1 = plm(arrest ~ tenure + p50_inc + tot_crimes + ro_black + ro_hisp + ro_white, data = offcri, model = "within", index = c("NUID","month", "unit"))
reg5_2 = plm(arrest ~ tenure + p50_inc + tot_crimes + ro_black + ro_hisp + ro_white, data = offcri, model = "between", index = c("NUID","month", "unit"))
reg5_3 = plm(arrest ~ tenure + p50_inc + tot_crimes + ro_black + ro_hisp + ro_white, data = offcri, model = "fd", index = c("NUID","month", "unit"))
```
```{r}
summary(reg5_1)
```
```{r}
summary(reg5_2)
```
```{r}
summary(reg5_3)
```


```{r}
rmarkdown::render('A3.Rmd', 'pdf_document')

```

